FROM python:3.9-slim

WORKDIR /app

COPY ./ui/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./ui .

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]