FROM python:3.9-slim

WORKDIR /app

COPY ./api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src
COPY ./data ./data
COPY ./api/main.py .

CMD ["python", "main.py"]