apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api
  labels:
    app: ml-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
      - name: ml-api
        image: your-docker-image-name:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: S3_BUCKET_NAME
          value: "mlopsarp-bk1"
        - name: S3_PREFIX
          value: "mlops_practive"
        - name: S3_URL
          value: "s3://mlopsarp-bk1/mlops_practive/"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"